### PR TITLE
add icons to the theme

### PR DESCRIPTION
**Pull request by slocker3**

### CODE REVIEW

**Comment by slocker3** [comment]
@philcable #reviewmerge

**Comment by philcable** [comment]
@slocker3 I have questions :)

We have optimized SVGs for both versions of the signature in https://github.com/washingtonstateuniversity/murrow.wsu.edu/tree/master/images. Are the signatures included here different? And why are there two horizontal signatures?

I also have optimized versions of the `degree`, `people`, `program`, and `topic` SVGs - if the versions included in this branch are the same as the initial ones @allenjohns created, let's use the already optimized versions and get the new additions optimized.

**Comment by slocker3** [comment]
@philcable I don't have any quality answers :) 

I will get these cleaned up. What do you use for optimization?

**Comment by philcable** [comment]
@slocker3 Haha, no problem!

I have a commit almost ready to go - it'd be done if I hadn't sabotaged myself right at the end :)

I've been using http://petercollingridge.appspot.com/svg-optimiser, but sometimes it optimizes a little too well. https://simon.html5.org/tools/js/svg-optimizer/ is another option.

**Comment by philcable** [comment]
Let's have @jeremyfelt #reviewmerge now :)

**Review by jeremyfelt — APPROVED** [review]
Looking good!

**Pull request merged**
